name: CubeCore
version: ${project.version}
main: de.cubeisland.cubeengine.core.bukkit.BukkitBootstrapper
website: http://cubeisland.de
description: "Core plugin for all the Cube plugins"
authors:
  - "Cube Island"
