name: CubeEngine
version: "${project.version}"
main: de.cubeisland.CubeEngine.CubeEngine
#commands:
depend: []
softdepend: []
database: false
website: "http://cubeisland.de"
description: ""
author: "Cube Island"
authors:
  - "Cube Island"
load: postworld
#permissions:
