debug: true
cubewar:
  language: de
  ranks:
    Wegelagerer:
      deathmodifier: 45
      killmodifier: 50
      killpointlimit: -100
    Vagabund:
      deathmodifier: 45
      killmodifier: 50
      killpointlimit: 0
    Schläger:
      deathmodifier: 90
      killmodifier: 100
      killpointlimit: 250
    Bandit:
      deathmodifier: 225
      killmodifier: 250
      killpointlimit: 600
    Plünderer:
      deathmodifier: 540
      killmodifier: 600
      killpointlimit: 1500
    Söldner:
      deathmodifier: 1350
      killmodifier: 1500
      killpointlimit: 3500
    Berserker:
      deathmodifier: 3150
      killmodifier: 3500
      killpointlimit: 8000
    Gladiator:
      deathmodifier: 7200
      killmodifier: 8000
      killpointlimit: 20000
    Held:
      deathmodifier: 18000
      killmodifier: 20000
      killpointlimit: 100000
  killpoint:
     min: -100
     max: 200000
  chat:
    useCWChat: false
    tagreplace: [CWTEAM]

  area:
    safezone:

    warland:

    wildland:

    team_default:
      economy:
        bank: false
      power:
        haspermpower: false
        permpower:
        powerboost: 0
        powerloss: true
        powergain: true
      pvp:
        PvP: true
        damage: true 
        friendlyfire: false
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: true
        destroy: false
      protect:
        - DISPENSER
        - CHEST
        - FURNACE
        - BURNING_FURNACE
        - WOODEN_DOOR
        - JUKEBOX
        - DIODE_BLOCK_OFF
        - DIODE_BLOCK_ON
        - TRAP_DOOR
        - FENCE_GATE
        - ENCHANTMENT_TABLE
        - BREWING_STAND
        - CAULDRON
      use:
        fire: true
        lava: false
        water: false
      denycommands:
        - killallandeverything
        
    arena_default:
      
   