debug: true
cubewar:
  language: de
  ranks:
    Wegelagerer:
      deathmodifier: 45
      killmodifier: 50
      killpointlimit: -100
    Vagabund:
      deathmodifier: 45
      killmodifier: 50
      killpointlimit: 0
    Schläger:
      deathmodifier: 90
      killmodifier: 100
      killpointlimit: 250
    Bandit:
      deathmodifier: 225
      killmodifier: 250
      killpointlimit: 600
    Plünderer:
      deathmodifier: 540
      killmodifier: 600
      killpointlimit: 1500
    Söldner:
      deathmodifier: 1350
      killmodifier: 1500
      killpointlimit: 3500
    Berserker:
      deathmodifier: 3150
      killmodifier: 3500
      killpointlimit: 8000
    Gladiator:
      deathmodifier: 7200
      killmodifier: 8000
      killpointlimit: 20000
    Held:
      deathmodifier: 18000
      killmodifier: 20000
      killpointlimit: 100000
  killpoint:
     min: -100
     max: 200000
     
  chat:
    useCWChat: false
    tagreplace: [CWTEAM]

  area:
    safezone:
      power:
        haspermpower: false
        permpower: 0
        powerboost: 0
        powerloss: false
        powergain: false
      pvp:
        PvP: false
        damage: false 
        friendlyfire: false
        spawnprotectseconds: 3
      monster: 
        spawn: false
        damage: false
      build:
        place: true
        destroy: true
      protect: []
      use:
        fire: false
        lava: false
        water: false
      denycommands: []
      
    warland:
      power:
        haspermpower: false
        permpower: 0
        powerboost: 0
        powerloss: true
        powergain: true
      pvp:
        PvP: true
        damage: true 
        friendlyfire: true
        spawnprotectseconds: 2
      monster: 
        spawn: true
        damage: true
      build:
        place: false
        destroy: false
      protect: []
      use:
        fire: true
        lava: false
        water: false
      denycommands:
        - spawn
        - warp
        - home

    wildland:
      power:
        haspermpower: false
        permpower: 0
        powerboost: 0
        powerloss: true
        powergain: true
      pvp:
        PvP: true
        damage: true 
        friendlyfire: false
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: false
        destroy: false
      protect: []
      use:
        fire: false
        lava: false
        water: false
      denycommands: []

    team_default:
      economy:
        bank: false
        ##### economy einbindung
      power:
        haspermpower: false
        permpower: 0
        powerboost: 0
        powerloss: true
        powergain: true
      pvp:
        PvP: true
        damage: true 
        friendlyfire: false
        spawnprotectseconds: 3
        #P+1 or P-1  changeDamage with Percentage
        #S5          setDamage to
        #1 or -1     changeDamage
        damagemodifier: P-30
      monster: 
        spawn: true
        damage: true
      build:
        place: false
        destroy: false
      protect:
        - DISPENSER
        - CHEST
        - FURNACE
        - BURNING_FURNACE
        - WOODEN_DOOR
        - JUKEBOX
        - DIODE_BLOCK_OFF
        - DIODE_BLOCK_ON
        - TRAP_DOOR
        - FENCE_GATE
        - ENCHANTMENT_TABLE
        - BREWING_STAND
        - CAULDRON
      use:
        fire: true
        lava: false
        water: false
      denycommands: []
        
    arena_default:
      economy:
        bank: false
      power:
        haspermpower: false
        permpower: 0
        powerboost: 0
        powerloss: true
        powergain: true
      pvp:
        PvP: true
        damage: true 
        friendlyfire: true
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: false
        destroy: false
      protect: []
      use:
        fire: true
        lava: false
        water: false
      denycommands:
        - spawn
        - warp
        - home