debug: true
cubewar:
  language: de
  ranks:
    Wegelagerer:
      deathmodifier: 45
      killmodifier: 50
      killpointlimit: -100
    Vagabund:
      deathmodifier: 45
      killmodifier: 50
      killpointlimit: 0
    Schläger:
      deathmodifier: 90
      killmodifier: 100
      killpointlimit: 250
    Bandit:
      deathmodifier: 225
      killmodifier: 250
      killpointlimit: 600
    Plünderer:
      deathmodifier: 540
      killmodifier: 600
      killpointlimit: 1500
    Söldner:
      deathmodifier: 1350
      killmodifier: 1500
      killpointlimit: 3500
    Berserker:
      deathmodifier: 3150
      killmodifier: 3500
      killpointlimit: 8000
    Gladiator:
      deathmodifier: 7200
      killmodifier: 8000
      killpointlimit: 20000
    Held:
      deathmodifier: 18000
      killmodifier: 20000
      killpointlimit: 100000
  killpoint:
     min: -100
     max: 200000
  chat:
    useCWChat: false
    tagreplace: [CWTEAM]
  area:
    safezone:
      pvp:
        PvP: false
        damage: false 
        friendlyfire: false
        spawnprotectseconds: 0
      monster: 
        spawn: false
        damage: false
      build:
        place: false
        destroy: false
      use:
        fire: false
        lava: false
        water: false
      power:
        powerloss: false
        powergain: true
      denycommands:
        - killallandeverything
    warland:
      pvp:
        PvP: true
        damage: true
        friendlyfire: true
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: false
        destroy: true
      use:
        fire: true
        lava: false
        water: false
      power:
        powerloss: true
        powergain: true
      denycommands:
        - home
        - sethome
        - spawn
        - tphere
        - tp
        - warp
    wildland:
      pvp:
        PvP: true
        damage: true 
        friendlyfire: false
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: false
        destroy: false
      use:
        fire: false
        lava: false
        water: false
      power:
        powerloss: true
        powergain: true
      denycommands:
        - killallandeverything
    team_default:
      name:
        tag: '&6TAG'
        description: 'Default Team &6change me!&f'
      economy:
        bank: false
        startmoney: 0
      power:
        permanentpower: NULL
        powerboost: 0
      pvp:
        PvP: true
        damage: true 
        friendlyfire: false
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: true
        destroy: false
      protect:
        - DISPENSER
        - CHEST
        - FURNACE
        - BURNING_FURNACE
        - WOODEN_DOOR
        - JUKEBOX
        - DIODE_BLOCK_OFF
        - DIODE_BLOCK_ON
        - TRAP_DOOR
        - FENCE_GATE
        - ENCHANTMENT_TABLE
        - BREWING_STAND
        - CAULDRON
      use:
        fire: true
        lava: false
        water: false
      power:
        powerloss: true
        powergain: true
    arena_default:
      name:
        tag: '&6TAG'
        description: 'Default Team &6change me!&f'
      economy:
        bank: false
        startmoney: 0
      power:
        permanentpower: false
        permpower: 0
        powerboost: 0
      pvp:
        PvP: true
        damage: true 
        friendlyfire: false
        spawnprotectseconds: 3
      monster: 
        spawn: true
        damage: true
      build:
        place: true
        destroy: false
      protect:
        - DISPENSER
        - CHEST
        - FURNACE
        - BURNING_FURNACE
        - WOODEN_DOOR
        - JUKEBOX
        - DIODE_BLOCK_OFF
        - DIODE_BLOCK_ON
        - TRAP_DOOR
        - FENCE_GATE
        - ENCHANTMENT_TABLE
        - BREWING_STAND
        - CAULDRON
      use:
        fire: true
        lava: false
        water: false
      power:
        powerloss: true
        powergain: true  
   