name: CubeFly
version: "${project.version}"
main: de.cubeisland.CubeEngine.CubeEngine
#commands:
depend: 
  - CubeCore
softdepend: []
database: false
website: "http://cubeisland.de"
description: "Flying without CreativeMode"
author: "Cube Island"
authors:
  - "Cube Island"
load: postworld
#permissions:
