name: CubeFly
version: "${project.version}"
main: de.cubeisland.cubeengine.fly.CubeFly
commands:
  fly:
    usage: "/fly"
    description: "This is the base command of CubeFly"
depend: 
  - CubeCore
softdepend: []
database: false
website: "http://cubeisland.de"
description: "Flying without CreativeMode"
author: "Cube Island"
authors:
  - "Cube Island"
load: postworld
#permissions:
