name: "${project.name}"
version: "${project.version}"
main: "de.cubeisland.cubeengine.core.bukkit.BukkitCore"
website: "${project.parent.url}"
description: "${project.parent.description}"
load: STARTUP
authors:
  - "Cube Island"
