name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.${project.artifactId}.core.bukkit.BukkitCore"
website: "${project.parent.url}"
description: "${project.parent.description}"
authors:
  - "Cube Island"
