name: "${project.name}"
version: "${project.version}"
source-version: "${githead.branch}-${githead.commit}"
main: "de.cubeisland.engine.core.bukkit.BukkitCore"
website: "${project.parent.url}"
description: "${project.parent.description}"
author: "CubeEngineDev"
authors:
  - "quick_wango"
  - "Faithcaio"
  - "totokaka"
  - "boeserwolf91"
