name: "${project.name}"
version: "${project.version}"
source-version: "${githead.branch}-${githead.commit}"
main: "de.cubeisland.cubeengine.core.bukkit.BukkitCore"
website: "${project.parent.url}"
description: "${project.parent.description}"
#load: STARTUP
authors:
  - "Cube Island"
